# Generated by Django 3.2.9 on 2021-11-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=6, verbose_name='Patente')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('brand', models.CharField(max_length=30, verbose_name='Marca')),
                ('model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('in_service', models.BooleanField(verbose_name='En Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('fathers_last_name', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('mothers_last_name', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('active', models.BooleanField(verbose_name='Chofer Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('fathers_last_name', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('mothers_last_name', models.CharField(max_length=30, verbose_name='Apellido Materno')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='Origen')),
                ('destiny', models.CharField(max_length=50, verbose_name='Destino')),
                ('active', models.BooleanField(verbose_name='Ruta Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.driver')),
                ('passengers', models.ManyToManyField(to='rides.Passenger')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.route')),
            ],
        ),
    ]
